library(tidyverse)
library(stringr)
# read data
data <- read_csv("Master File of All Data.csv")

# add abbreviations from histology 
new_data <- data %>% mutate(`Tissue Type From Abbreviation` = 
                              case_when(
                   ?            str_starts(`Block ID #`, "AA") ~ "Adrenocortical Adenoma",
                                str_starts(`Block ID #`, "ACC") ~ "Acinic Cell Carcinoma",
                                str_starts(`Block ID #`, "ACYSC") ~ "Adenoid Cystic Carcinoma"?
                                str_starts(`Block ID #`, "ADC") ~ "Adrenal Gland",
                                str_starts(`Block ID #`, "ADCC") ~ "Adrenocortical Carcinoma",
                                str_starts(`Block ID #`, "ADV") ~ "Adenovirus?,
                                str_starts(`Block ID #`, "AFX") ~ "Atypical Fibroxanthoma",
                                str_starts(`Block ID #`, "AITL") ~ "Angioimmunoblastic T-cell Lymphoma",
                                str_starts(`Block ID #`, ?AK") ~ "Actinic Keratosis",
                                str_starts(`Block ID #`, "ALCL") ~ "Anaplastic Large Cell Lymphoma",
                                str_starts(`Block ID #`, "AM") ~ "Amniotic Membrane",
                                str_start?(`Block ID #`, "AMD") ~ "Amyloid",
                                str_starts(`Block ID #`, "AML") ~ "Acute Myeloid Leukemia",
                                str_starts(`Block ID #`, "AMLP") ~ "Angiomyolipoma",
                                str_starts(`?lock ID #`, "AmpADCA") ~ "Ampullary Adenocarcinoma",
                                str_starts(`Block ID #`, "APX") ~ "Appendix",
                                str_starts(`Block ID #`, "AS") ~ "Angiosarcoma",
                                str_starts(`?lock ID #`, "ASIN") ~ "Anal Squamous Intraepithelial Neoplasia",
                                str_starts(`Block ID #`, "ASPS") ~ "Alveolar Soft Part Sarcoma",
                                str_starts(`Block ID #`, "AST") ~ "Astrocytoma",
             ?                  str_starts(`Block ID #`, "AT") ~ "Adenomatoid Tumor",
                                str_starts(`Block ID #`, "ATLL") ~ "Adult T-cell Lymphoma/Leukemia",
                                str_starts(`Block ID #`, "BADCA") ~ "Bladder Adenoc?rcinoma",
                                str_starts(`Block ID #`, "BCC") ~ "Basal Cell Carcinoma",
                                str_starts(`Block ID #`, "BCH") ~ "Bronchus",
                                str_starts(`Block ID #`, "BD") ~ "Bowen Diseas?",
                                str_starts(`Block ID #`, "BE") ~ "Barrett's Esophagus",
                                str_starts(`Block ID #`, "BIN") ~ "Blast Increase",
                                str_starts(`Block ID #`, "BL") ~ "Burkitt Lymphom?",
                                str_starts(`Block ID #`, "BLD") ~ "Bladder",
                                str_starts(`Block ID #`, "BM") ~ "Bone Marrow",
                                str_starts(`Block ID #`, "BONE") ~ "Bone Tissue",
              ?                 str_starts(`Block ID #`, "BPDCN") ~ "Blastic Plasmacytoid Dendritic Cell Neoplasm",
                                str_starts(`Block ID #`, "BRN") ~ "Brain",
                                str_starts(`Block ID #`, "BRN CEBL") ~ "Normal C?rebellum",
                                str_starts(`Block ID #`, "BRN CRB") ~ "Normal Cerebrum",
                                str_starts(`Block ID #`, "BRSA") ~ "Breast Sclerosing Adenosis",
                                str_starts(`Block ID #`, "B?TA") ~ "Breast Tubular Adenoma",
                                str_starts(`Block ID #`, "BSqCCA") ~ "Bladder, Squamous Cell Carcinoma",
                                str_starts(`Block ID #`, "BST") ~ "Breast",
                                str_starts?`Block ID #`, "BST-AD") ~ "Breast Adenoma",
                                str_starts(`Block ID #`, "BWL") ~ "Bowel",
                                str_starts(`Block ID #`, "CAND") ~ "Carcinoid",
                                str_starts(`Block ID #`, ?CB") ~ "Chondroblastoma",
                                str_starts(`Block ID #`, "CBD") ~ "Common Bile Duct",
                                str_starts(`Block ID #`, "CC") ~ "Choriocarcinoma",
                                str_starts(`Block ID #`, "CG?) ~ "Cystitis Glandularis",
                                str_starts(`Block ID #`, "CGIN") ~ "Cervical Glandular Intraepithelial Neoplasia",
                                str_starts(`Block ID #`, "CHD") ~ "Chondroid",
                                st?_starts(`Block ID #`, "CHL") ~ "Classical Hodgkin Lymphoma",
                                str_starts(`Block ID #`, "CH-RCC") ~ "Chromophobe RCC",
                                str_starts(`Block ID #`, "CIN I") ~ "Cervical Intraepithelial Neoplasia I",?                                str_starts(`Block ID #`, "CIN II") ~ "Cervical Intraepithelial Neoplasia II",
                                str_starts(`Block ID #`, "CIN III") ~ "Cervical Intraepithelial Neoplasia III",
                                st?_starts(`Block ID #`, "CJTA") ~ "Conjunctiva Tissue",
                                str_starts(`Block ID #`, "CL") ~ "Composite Lymphoma",
                                str_starts(`Block ID #`, "CM") ~ "Complete Mole",
                                s?r_starts(`Block ID #`, "CML") ~ "Chronic Myeloid Leukemia",
                                str_starts(`Block ID #`, "CMV") ~ "Cytomegalovirus",
                                str_starts(`Block ID #`, "CNDY") ~ "Condyloma",
                               ?str_starts(`Block ID #`, "COL") ~ "Colon",
                                str_starts(`Block ID #`, "COP") ~ "Cryptogenic Organizing Pneumonia",
                                str_starts(`Block ID #`, "CRC") ~ "Colorectal Adenocarcinoma",
                ?               str_starts(`Block ID #`, "CS") ~ "Chondrosarcoma",
                                str_starts(`Block ID #`, "CSA") ~ "Chronic Sialadenitis",
                                str_starts(`Block ID #`, "CSD") ~ "Castleman's Disease",
           ?                    str_starts(`Block ID #`, "CSL") ~ "Cat Scratch Lymphadenitis (Bartonella Henselae)",
                                str_starts(`Block ID #`, "CUP") ~ "Carcinoma of Unknown Primary Origin",
                                str_starts(`Bl?ck ID #`, "CVC") ~ "Cervical Carcinoma",
                                str_starts(`Block ID #`, "CVM") ~ "Cervical Metaplasia",
                                str_starts(`Block ID #`, "CVX") ~ "Cervix",
                                str_starts(`Block ?D #`, "CVX-SqCCA") ~ "Squamous Cell Carcinoma of Cervix",
                                str_starts(`Block ID #`, "CYST") ~ "Epidermal Cyst",
                                str_starts(`Block ID #`, "DCIS") ~ "Duct Carcinoma in situ, Breast",
            ?                   str_starts(`Block ID #`, "DDLPS") ~ "Dedifferentiated Liposarcoma",
                                str_starts(`Block ID #`, "DF") ~ "Dermatofibroma",
                                str_starts(`Block ID #`, "DFSP") ~ "Dermatofibrosarcom? Protuberans",
                                str_starts(`Block ID #`, "DGRM") ~ "Dysgerminoma",
                                str_starts(`Block ID #`, "DLBCL") ~ "Diffuse Large B-cell Lymphoma",
                                str_starts(`Block ID #`, ?DMG") ~ "Diffuse Midline Glioma",
                                str_starts(`Block ID #`, "DUOCA") ~ "Duodenal Carcinoma",
                                str_starts(`Block ID #`, "DYSN") ~ "Dysplastic Nevus",
                                str_starts(`B?ock ID #`, "E") ~ "Esophagus",
                                str_starts(`Block ID #`, "EADC") ~ "Esophagus Adenocarcinoma",
                                str_starts(`Block ID #`, "EBV") ~ "Epstein Barr Virus Infected Tissue",
                          ?     str_starts(`Block ID #`, "EC") ~ "Embryonal Carcinoma",
                                str_starts(`Block ID #`, "ECAS") ~ "Eccrine Acrospiroma",
                                str_starts(`Block ID #`, "Echinococcus") ~ "Echinococcus Infected Tissue"?
                                str_starts(`Block ID #`, "EIN") ~ "Endometrial Intraepithelial Neoplasia",
                                str_starts(`Block ID #`, "EMCA") ~ "Endometrial Carcinoma",
                                str_starts(`Block ID #`,?"EMCA-MT") ~ "Endometrial Carcinoma - Mixed Type (Type I + Type II)",
                                str_starts(`Block ID #`, "ENCH") ~ "Enchondroma of the Bone",
                                str_starts(`Block ID #`, "ENDO") ~ "Endometriosis",
        ?                       str_starts(`Block ID #`, "EPC") ~ "Encapsulated Papillary Carcinoma of the Breast",
                                str_starts(`Block ID #`, "ESqCC") ~ "Esophagus Squamous Cell Carcinoma",
                                str_starts(`?lock ID #`, "ET") ~ "Essential Thrombocythemia",
                                str_starts(`Block ID #`, "EWS") ~ "Ewing's Sarcoma",
                                str_starts(`Block ID #`, "FA") ~ "Fibroadenoma",
                                str_start?(`Block ID #`, "FAT") ~ "Fat (Adipose)",
                                str_starts(`Block ID #`, "FCCL") ~ "Follicular Center Cell Lymphoma",
                                str_starts(`Block ID #`, "FDCS") ~ "Follicular Dendritic Cell Sarcoma",
         ?                      str_starts(`Block ID #`, "FH") ~ "Follicular Hyperplasia",
                                str_starts(`Block ID #`, "FIB") ~ "Fibromatosis",
                                str_starts(`Block ID #`, "FL") ~ "Follicular Lymphoma",
     ?                          str_starts(`Block ID #`, "FLIS") ~ "Follicular Lymphoma in situ",
                                str_starts(`Block ID #`, "FS") ~ "Fibrosarcoma",
                                str_starts(`Block ID #`, "FTA") ~ "Follicular Thyro?d Adenoma",
                                str_starts(`Block ID #`, "FTC") ~ "Follicular Thyroid Carcinoma",
                                str_starts(`Block ID #`, "FTK") ~ "Fetal Kidney",
                                str_starts(`Block ID #`, "FTL") ? "Fetal Liver",
                                str_starts(`Block ID #`, "FTLUG") ~ "Fetal Lung",
                                str_starts(`Block ID #`, "FTS") ~ "Fetal Spleen",
                                str_starts(`Block ID #`, "FTUB") ~ "Fallopia? tube",
                                str_starts(`Block ID #`, "GB") ~ "Gall bladder",
                                str_starts(`Block ID #`, "GBADCA") ~ "Gall Bladder Adenocarcinoma",
                                str_starts(`Block ID #`, "GCNIS") ~?"Germ Cell Neoplasia in situ",
                                str_starts(`Block ID #`, "GCTB") ~ "Giant Cell Tumor of the Bone",
                                str_starts(`Block ID #`, "GEJCA") ~ "Gastroesophageal Junction Carcinoma",
                   ?            str_starts(`Block ID #`, "Giardia") ~ "Giardia Infected Tissue",
                                str_starts(`Block ID #`, "GIST") ~ "Gastrointestinal Stromal Tumor",
                                str_starts(`Block ID #`, "GLB") ~ "Glioblastom?, Brain",
                                str_starts(`Block ID #`, "GLNR") ~ "Ganglioneuroma",
                                str_starts(`Block ID #`, "GNBI") ~ "Ganglioneuroblastoma Intermixed",
                                str_starts(`Block ID #`, "G?A") ~ "Granuloma",
                                str_starts(`Block ID #`, "GRACT") ~ "Granular Cell Tumor",
                                str_starts(`Block ID #`, "GrCT") ~ "Granulosa Cell Tumor",
                                str_starts(`Block ID #`? "GZL") ~ "Gray-Zone Lymphoma",
                                str_starts(`Block ID #`, "HA") ~ "Hepatocellular Adenoma",
                                str_starts(`Block ID #`, "HB") ~ "Hemangioblastoma",
                                str_starts(`Bloc? ID #`, "HCC") ~ "Hepatocellular Carcinoma",
                                str_starts(`Block ID #`, "HCL") ~ "Hairy Cell Leukemia",
                                str_starts(`Block ID #`, "HCS") ~ "Histiocytic Sarcoma",
                                s?r_starts(`Block ID #`, "HDN") ~ "Hepatic Dysplastic Nodule",
                                str_starts(`Block ID #`, "HET") ~ "Hemangioendothelioma",
                                str_starts(`Block ID #`, "HG") ~ "Hemangioma",
                          ?     str_starts(`Block ID #`, "HGPIN") ~ "High-grade Prostate Intraepithelial Neoplasia",
                                str_starts(`Block ID #`, "HHV-6") ~ "Human Herpesvirus-6 Infected Tissue",
                                str_starts(`Block ID #`, "H?L") ~ "Histiocytic Necrotizing Lymphadenitis (aka Kikuchi Fujimoto disease)",
                                str_starts(`Block ID #`, "HP") ~ "Helicobacter pylori",
                                str_starts(`Block ID #`, "HPD") ~ "Hirschsprung's Disease"?
                                str_starts(`Block ID #`, "HRT") ~ "Heart Muscle",
                                str_starts(`Block ID #`, "HS") ~ "Hernia Sac",
                                str_starts(`Block ID #`, "HSV") ~ "Herpes Simplex Virus Infect?d Tissue",
                                str_starts(`Block ID #`, "ICC") ~ "Intrahepatic Cholangiocarcinoma",
                                str_starts(`Block ID #`, "IDC") ~ "Invasive Ductal Carcinoma, Breast",
                                str_start?(`Block ID #`, "ILC") ~ "Invasive Lobular Carcinoma, Breast",
                                str_starts(`Block ID #`, "ILD") ~ "Interstitial Lung Disease",
                                str_starts(`Block ID #`, "IMT") ~ "Inflammatory Myofibroblastic Tum?r",
                                str_starts(`Block ID #`, "INT") ~ "Inflammatory/Necrotizing Tumor",
                                str_starts(`Block ID #`, "IP") ~ "Inverted Papilloma (Sinonasal)",
                                str_starts(`Block ID ?`, "KA") ~ "Keratoacanthoma",
                                str_starts(`Block ID #`, "KID") ~ "Kidney",
                                str_starts(`Block ID #`, "KID-TR") ~ "Kidney Transplant Reject",
                                str_starts(`Block ID ?`, "KS") ~ "Kaposi's sarcoma",
                                str_starts(`Block ID #`, "LADCA") ~ "Lung Adenocarcinoma",
                                str_starts(`Block ID #`, "LASC") ~ "Lung Adenosquamous Carcinoma",
                                str?starts(`Block ID #`, "LBCL-INT") ~ "Large B-cell Intermediate Lymphoma",
                                str_starts(`Block ID #`, "LBL") ~ "Lymphoblastic Lymphoma",
                                str_starts(`Block ID #`, "LCH") ~ "Langerhans Cell Histiocy?osis",
                                str_starts(`Block ID #`, "LCIS") ~ "Lobular Carcinoma in situ, Breast",
                                str_starts(`Block ID #`, "LCT") ~ "Leydig Cell Tumor",
                                str_starts(`Block ID #`, "?ES") ~ "Liver Embryonal Sarcoma",
                                str_starts(`Block ID #`, "LGFMS") ~ "Low-grade Fibromyxoid Sarcoma",
                                str_starts(`Block ID #`, "LIM") ~ "Leiomyoma",
                                str_starts?`Block ID #`, "LIP") ~ "Lipoma",
                                str_starts(`Block ID #`, "LIV") ~ "Liver",
                                str_starts(`Block ID #`, "LLCCA") ~ "Lung Large Cell Carcinoma",
                                str_starts(`Block I? #`, "LMS") ~ "Leiomyosarcoma",
                                str_starts(`Block ID #`, "LN") ~ "Lymph Node",
                                str_starts(`Block ID #`, "LNECA") ~ "Lung Neuroendocrine Carcinoma",
                                str_starts(`?lock ID #`, "LPL") ~ "Lymphoplasmacytic Lymphoma",
                                str_starts(`Block ID #`, "LPS") ~ "Liposarcoma (Well-Differentiated)",
                                str_starts(`Block ID #`, "LSqCC") ~ "Lung Squamous Cell Carcinoma",
  ?                             str_starts(`Block ID #`, "LUG") ~ "Lung",
                                str_starts(`Block ID #`, "MANEC") ~ "Mixed Adenoneuroendocrine Carcinoma",
                                str_starts(`Block ID #`, "MCC") ~ "Merkel Cell?Carcinoma",
                                str_starts(`Block ID #`, "MCL") ~ "Mantle Cell Lymphoma",
                                str_starts(`Block ID #`, "MEC") ~ "Mucoepidermoid Carcinoma",
                                str_starts(`Block ID #`, "ME?") ~ "Melanoma",
                                str_starts(`Block ID #`, "MEL-DES") ~ "Desmoplastic Melanoma",
                                str_starts(`Block ID #`, "MELIS") ~ "Melanoma in situ",
                                str_starts(`Block ID #`,?"MEMA") ~ "Myoepithelioma",
                                str_starts(`Block ID #`, "MES") ~ "Mesothelioma",
                                str_starts(`Block ID #`, "Met-AMP") ~ "Metastatic Ampullary Adenocarcinoma",
                                str_s?arts(`Block ID #`, "Met-BrCA") ~ "Metastatic Breast Carcinoma",
                                str_starts(`Block ID #`, "Met-CRC") ~ "Metastatic Colorectal Carcinoma",
                                str_starts(`Block ID #`, "Met-GC") ~ "Metastatic Gastri? Carcinoma",
                                str_starts(`Block ID #`, "Met-LAD") ~ "Metastatic Lung Adenocarcinoma",
                                str_starts(`Block ID #`, "Met-LLCCA") ~ "Metastatic Lung Large Cell Carcinoma",
                           ?    str_starts(`Block ID #`, "Met-MEL") ~ "Metastatic Melanoma",
                                str_starts(`Block ID #`, "Met-OVCA") ~ "Metastatic Ovarian Carcinoma",
                                str_starts(`Block ID #`, "Met-PCA") ~ "Metastatic Prosta?e Carcinoma",
                                str_starts(`Block ID #`, "Met-PDA") ~ "Metastatic Pancreatic Ductal Adenocarcinoma",
                                str_starts(`Block ID #`, "Met-RCC") ~ "Metastatic Renal Cell Carcinoma",
                    ?           str_starts(`Block ID #`, "Met-SqCC") ~ "Metastatic Squamous Cell Carcinoma",
                                str_starts(`Block ID #`, "Met-UTC") ~ "Metastatic Urothelial Carcinoma",
                                str_starts(`Block ID #`, "MF") ? "Mycosis Fungoides",
                                str_starts(`Block ID #`, "MGCT") ~ "Mixed Germ Cell Tumor",
                                str_starts(`Block ID #`, "MGM") ~ "Meningioma",
                                str_starts(`Block ID #`, "MH")?~ "Mesothelial Hyperplasia",
                                str_starts(`Block ID #`, "MLPS") ~ "Myxoid Liposarcoma",
                                str_starts(`Block ID #`, "MMMT") ~ "Malignant Mixed Müllerian Tumor",
                                str_?tarts(`Block ID #`, "MPN") ~ "Myeloproliferative Neoplasm Bone Marrow",
                                str_starts(`Block ID #`, "MPNST") ~ "Malignant Peripheral Nerve Sheath Tumor",
                                str_starts(`Block ID #`, "MT") ~ "Mediast?nal Tumor",
                                str_starts(`Block ID #`, "MTC") ~ "Medullary Thyroid Carcinoma",
                                str_starts(`Block ID #`, "MTT") ~ "Malignant Triton Tumor",
                                str_starts(`Block ID #`? "MUS") ~ "Skeletal Muscle",
                                str_starts(`Block ID #`, "MZL") ~ "Marginal Zone Lymphoma",
                                str_starts(`Block ID #`, "NAFLD") ~ "Non-Alcoholic Fatty Liver Disease",
                              ? str_starts(`Block ID #`, "NasophaCA") ~ "Nasopharyngeal Carcinoma",
                                str_starts(`Block ID #`, "NB") ~ "Neuroblastoma",
                                str_starts(`Block ID #`, "NC") ~ "NUT Carcinoma",
                       ?        str_starts(`Block ID #`, "NECA") ~ "Neuroendocrine Carcinoma",
                                str_starts(`Block ID #`, "NERV") ~ "Nerve tissue",
                                str_starts(`Block ID #`, "NEUM") ~ "Neuroma",
                        ?       str_starts(`Block ID #`, "Nevus") ~ "Nevus (Intradermal)",
                                str_starts(`Block ID #`, "NF") ~ "Neurofibroma",
                                str_starts(`Block ID #`, "NKL") ~ "NK-Cell Lymphoma",
                       ?        str_starts(`Block ID #`, "NLPHL") ~ "Nodular Lymphocyte Predominant, Hodgkin Lymphoma",
                                str_starts(`Block ID #`, "ODG") ~ "Oligodendroglioma",
                                str_starts(`Block ID #`, "ONCA") ~ "Oncoc?tic Carcinoma",
                                str_starts(`Block ID #`, "OS") ~ "Osteosarcoma",
                                str_starts(`Block ID #`, "OSqCC") ~ "Oral Squamous Cell Carcinoma",
                                str_starts(`Block ID #`, "O?BT") ~ "Ovarian Brenner Tumor",
                                str_starts(`Block ID #`, "OVCCC") ~ "Ovarian Clear Cell Carcinoma",
                                str_starts(`Block ID #`, "OVEC") ~ "Ovarian Endometrioid Carcinoma",
                       ?        str_starts(`Block ID #`, "OVMC") ~ "Ovarian Mucinous Carcinoma",
                                str_starts(`Block ID #`, "OVMN") ~ "Ovarian Mucinous Neoplasm",
                                str_starts(`Block ID #`, "OVR") ~ "Ovary",
            ?                   str_starts(`Block ID #`, "OVSC") ~ "Ovarian Serous Carcinoma",
                                str_starts(`Block ID #`, "OVSCT") ~ "Ovary Steroid Cell Tumor",
                                str_starts(`Block ID #`, "OVSN") ~ "Ovarian Se?ous Neoplasm",
                                str_starts(`Block ID #`, "OVUC") ~ "Ovarian Undifferentiated Carcinoma",
                                str_starts(`Block ID #`, "P.cari") ~ "Pneumocystis jirovecii(carinii)",
                                ?tr_starts(`Block ID #`, "PA") ~ "Pleomorphic Adenoma",
                                str_starts(`Block ID #`, "PAN") ~ "Pancreas",
                                str_starts(`Block ID #`, "PanIN") ~ "Pancreatic Intraepithelial Neoplasia",
               ?                str_starts(`Block ID #`, "PARV") ~ "Parvovirus",
                                str_starts(`Block ID #`, "PBCH") ~ "Prostate Basal Cell Hyperplasia",
                                str_starts(`Block ID #`, "PC") ~ "Pleomorphic Carcinoma",?                                str_starts(`Block ID #`, "PCA") ~ "Prostate Carcinoma",
                                str_starts(`Block ID #`, "PCFCL") ~ "Primary Cutaneous Follicular Cell Lymphoma",
                                str_starts(`Block ID #?, "PCM") ~ "Plasma Cell Myeloma",
                                str_starts(`Block ID #`, "PCT") ~ "Plasmacytoma",
                                str_starts(`Block ID #`, "PD") ~ "Paget's Disease (of the Breast/Skin)",
                                str?starts(`Block ID #`, "PDA") ~ "Pancreatic Ductal Adenocarcinoma",
                                str_starts(`Block ID #`, "PDTC") ~ "Poorly Differentiated Thyroid Carcinoma",
                                str_starts(`Block ID #`, "PEC") ~ "Perivascular ?pithelioid Cell Tumor, PEComa",
                                str_starts(`Block ID #`, "PEL") ~ "Primary Effusion Lymphoma",
                                str_starts(`Block ID #`, "PGM") ~ "Paraganglioma",
                                str_starts(`Bl?ck ID #`, "PH") ~ "Pulmonary Hamartoma",
                                str_starts(`Block ID #`, "PHEO") ~ "Pheochromocytoma",
                                str_starts(`Block ID #`, "PIT") ~ "Pancreatic Islet Cell Tumor",
                               ?str_starts(`Block ID #`, "PLC") ~ "Placenta",
                                str_starts(`Block ID #`, "PM") ~ "Partial Mole",
                                str_starts(`Block ID #`, "PMCN") ~ "Pancreatic Mucinous Cystic Neoplasm",
                       ?        str_starts(`Block ID #`, "PMP") ~ "Pseudomyxoma Peritonei",
                                str_starts(`Block ID #`, "PNT") ~ "Pancreatic Neuroendocrine Tumor",
                                str_starts(`Block ID #`, "POC") ~ "Product of Conceptio?",
                                str_starts(`Block ID #`, "POLV") ~ "Polyoma Virus",
                                str_starts(`Block ID #`, "PPC") ~ "Primary Peritoneal Carcinoma",
                                str_starts(`Block ID #`, "PRCC") ~ "Pap?llary Renal Cell Carcinoma",
                                str_starts(`Block ID #`, "PSCC") ~ "Prostate Small Cell Carcinoma",
                                str_starts(`Block ID #`, "PSCN") ~ "Pancreatic Serous Cystic Neoplasm",
                       ?        str_starts(`Block ID #`, "PSqCC") ~ "Penis Squamous Cell Carcinoma",
                                str_starts(`Block ID #`, "PST") ~ "Prostate",
                                str_starts(`Block ID #`, "PT") ~ "Phyllodes Tumor, Breast",
         ?                      str_starts(`Block ID #`, "PTC") ~ "Papillary Thyroid Carcinoma",
                                str_starts(`Block ID #`, "PTCL") ~ "Peripheral T-cell Lymphoma, NOS",
                                str_starts(`Block ID #`, "PTD") ~ "?arathyroid",
                                str_starts(`Block ID #`, "PTD-AD") ~ "Parathyroid Adenoma",
                                str_starts(`Block ID #`, "PTU") ~ "Pituitary",
                                str_starts(`Block ID #`, "PTU-AD") ~ "Pi?uitary Adenoma",
                                str_starts(`Block ID #`, "PUNLMP") ~ "Papillary Urothelial Neoplasm of Low Malignant Potential",
                                str_starts(`Block ID #`, "PV") ~ "Polycythemia Vera",
                        ?       str_starts(`Block ID #`, "RCC") ~ "Renal Cell Carcinoma",
                                str_starts(`Block ID #`, "RCL") ~ "Recent Corpus Luteum",
                                str_starts(`Block ID #`, "RDD") ~ "Rosai Dorfman Disease",
          ?                     str_starts(`Block ID #`, "RLAP") ~ "Reactive Lymphadenopathy",
                                str_starts(`Block ID #`, "RMS") ~ "Rhabdomyosarcoma",
                                str_starts(`Block ID #`, "RO") ~ "Renal Oncocytoma",
 ?                              str_starts(`Block ID #`, "RT") ~ "Rhabdoid Tumor",
                                str_starts(`Block ID #`, "RUA") ~ "Reactive Urothelial Atypia",
                                str_starts(`Block ID #`, "SAR") ~ "Sarcoidosis"?
                                str_starts(`Block ID #`, "SC") ~ "Sarcomatoid Carcinoma",
                                str_starts(`Block ID #`, "SCLC") ~ "Small Cell Lung Carcinoma",
                                str_starts(`Block ID #`, "SCM") ~ "Sp?ndle Cell Melanoma",
                                str_starts(`Block ID #`, "SCT") ~ "Sertoli Cell Tumor",
                                str_starts(`Block ID #`, "SDH-RCC") ~ "SDH-Deficient RCC",
                                str_starts(`Block ID #`,?"SebacAD") ~ "Sebaceous Adenoma",
                                str_starts(`Block ID #`, "SebacCA") ~ "Sebaceous Carcinoma",
                                str_starts(`Block ID #`, "SebacHP") ~ "Sebaceous Gland Hyperplasia",
                            ?   str_starts(`Block ID #`, "SEM") ~ "Seminoma",
                                str_starts(`Block ID #`, "SFT") ~ "Solitary Fibrous Tumor",
                                str_starts(`Block ID #`, "SG") ~ "Salivary Gland",
                                ?tr_starts(`Block ID #`, "SGO") ~ "Salivary Gland Oncocytoma",
                                str_starts(`Block ID #`, "SGSqCC") ~ "Salivary Gland Squamous Cell Carcinoma",
                                str_starts(`Block ID #`, "SK") ~ "Seborrheic Kerato?is",
                                str_starts(`Block ID #`, "SKN") ~ "Skin",
                                str_starts(`Block ID #`, "SLCT") ~ "Sertoli-Leydig Cell Tumor",
                                str_starts(`Block ID #`, "SLL") ~ "Small Lymphocy?ic Lymphoma",
                                str_starts(`Block ID #`, "CLL") ~ "Chronic Lymphocytic Leukemia",
                                str_starts(`Block ID #`, "SMBT") ~ "Seromucinous Borderline Tumor",
                                str_starts(`?lock ID #`, "SMU") ~ "Smooth Muscle",
                                str_starts(`Block ID #`, "SNIP") ~ "Sinonasal Inflammatory Polyp",
                                str_starts(`Block ID #`, "SO") ~ "Struma Ovarii",
                                str_s?arts(`Block ID #`, "SpCD") ~ "Spermatic Cord",
                                str_starts(`Block ID #`, "SPCL") ~ "Spindle Cell Lipoma",
                                str_starts(`Block ID #`, "SPIRO") ~ "Spirochetes",
                                str_?tarts(`Block ID #`, "SPN") ~ "Spleen",
                                str_starts(`Block ID #`, "SpSEM") ~ "Spermatocytic Seminoma",
                                str_starts(`Block ID #`, "SPZN") ~ "Spitz Nevus",
                                str_start?(`Block ID #`, "SS") ~ "Synovial Sarcoma",
                                str_starts(`Block ID #`, "SSqCC") ~ "Skin Squamous Cell Carcinoma",
                                str_starts(`Block ID #`, "STM") ~ "Stomach",
                                str_?tarts(`Block ID #`, "STM-CA-DIF") ~ "Stomach Carcinoma, Diffuse Type",
                                str_starts(`Block ID #`, "STM-CA-INT") ~ "Stomach Carcinoma, Intestinal Type",
                                str_starts(`Block ID #`, "SV") ~ "Seminal ?esicles",
                                str_starts(`Block ID #`, "SWM") ~ "Schwannoma",
                                str_starts(`Block ID #`, "SYN") ~ "Synovial Tissue",
                                str_starts(`Block ID #`, "TA") ~ "Colon, Tubular ?denoma",
                                str_starts(`Block ID #`, "TCL") ~ "T-cell Lymphoma",
                                str_starts(`Block ID #`, "TLFCK") ~ "Thyroid-Like Follicular Carcinoma of the Kidney",
                                str_starts(?Block ID #`, "TLGLL") ~ "T-cell Large Granular Lymphocytic Leukemia",
                                str_starts(`Block ID #`, "TMA") ~ "Tissue Microarray",
                                str_starts(`Block ID #`, "Toxo") ~ "Toxoplasma gondii",
           ?                    str_starts(`Block ID #`, "TSGCT") ~ "Tenosynovial Giant Cell Tumor",
                                str_starts(`Block ID #`, "TSL") ~ "Tonsil",
                                str_starts(`Block ID #`, "TSqCC") ~ "Thymic Squamous Cell C?rcinoma",
                                str_starts(`Block ID #`, "TST") ~ "Testis",
                                str_starts(`Block ID #`, "TTI") ~ "Teratoma - Immature",
                                str_starts(`Block ID #`, "TTM") ~ "Teratoma - Mat?re",
                                str_starts(`Block ID #`, "TYD") ~ "Thyroid",
                                str_starts(`Block ID #`, "TYM") ~ "Thymus",
                                str_starts(`Block ID #`, "TYMCA") ~ "Thymic Carcinoma",
          ?                     str_starts(`Block ID #`, "TYMT") ~ "Thymic Tumor (Thymoma)",
                                str_starts(`Block ID #`, "UCP") ~ "Undifferentiated (Anaplastic) Carcinoma of the Pancreas",
                                str_starts(`Block?ID #`, "Ureter") ~ "Ureter",
                                str_starts(`Block ID #`, "USC") ~ "Uterine Serous Carcinoma",
                                str_starts(`Block ID #`, "USS") ~ "Uterus Stromal Sarcoma",
                                str_start?(`Block ID #`, "USTS") ~ "Undifferentiated Soft Tissue Sarcoma",
                                str_starts(`Block ID #`, "UTC") ~ "Urothelial Carcinoma",
                                str_starts(`Block ID #`, "UTCIS") ~ "Urothelial Carcinoma in situ",
 ?                              str_starts(`Block ID #`, "UTD") ~ "Urothelial Dysplasia",
                                str_starts(`Block ID #`, "UTH") ~ "Urothelial Hyperplasia",
                                str_starts(`Block ID #`, "UTP") ~ "Urothelia? Papilloma",
                                str_starts(`Block ID #`, "UTS") ~ "Uterus",
                                str_starts(`Block ID #`, "VAS") ~ "Vas Deferens",
                                str_starts(`Block ID #`, "VIN III") ~ "Vulvar Intraep?thelial Neoplasia III",
                                str_starts(`Block ID #`, "VZV") ~ "Varicella Zoster Virus",
                                str_starts(`Block ID #`, "WART") ~ "Warthin Tumor",
                                str_starts(`Block ID #`,?"WDPM") ~ "Well Differentiated Papillary Mesothelioma",
                                str_starts(`Block ID #`, "WT") ~ "Wilm's Tumor",
                                str_starts(`Block ID #`, "XP11TRx-RCC") ~ "Xp11.2 Translocation Renal Cell Carcinoma",
?                               str_starts(`Block ID #`, "YST") ~ "Yolk Sac Tumor",
                                
                               
                                T ~ "Other"))

# Reorder data
new_data <- new_data[, c(1,2,35,3:34)]

# Fix ?pecial blocks
new_data %>% filter(`Tissue Type From Abbreviation` == "Other") %>% pull(`Block ID #`)
special_blocks <- c("Umbilical Cord A", "Umbilical Cord B", "Umbilical Cord C", "Gigi's Tumor", "Infected Tissue")
new_data[new_data$`Block ID #` %in% spec?al_blocks, "Tissue Type From Abbreviation"] <- "Special Blocks"

# Calculate summary statistics
stats <- new_data %>% 
  group_by(`Tissue Type From Abbreviation`) %>% 
  summarise("Total Number Of Blocks" = n(), 
            "Total Number of Unsourced Bloc?s" = sum(is.na(Source)),
            "Percent Unsourced" = round(100 * sum(is.na(Source))/n())) %>% 
  arrange("Total Number Of Blocks")

write_csv(new_data, "Final Master File.csv", na = "")
write_csv(stats, "Non-Sourced Statistics.csv", na = "")
